name: Timberwolf
version: 0.0.1
author: Sam Wolfson
main: com.samwolfson.timberwolf.Timberwolf
api-version: 1.16
commands:
  undochop:
    description: Undo your last tree chop.
    usage: /undochop
    permission: timberwolf.undochop
permissions:
  timberwolf.undochop:
    description: Allow player to undo tree chop.
  timberwolf.chop:
    description: Allow player to auto-chop trees.

