name: Timberwolf
version: 0.0.1
author: Sam Wolfson
main: com.samwolfson.timberwolf.Timberwolf
api-version: 1.16
commands:
  undochop:
    description: Undo your last tree chop.
    usage: /undochop
    permission: timberwolf.undochop
  listchops:
    description: List all your chops.
    usage: /listchops
    permission: timberwolf.listchops
  blesschop:
    description: Bless a tool for chopping.
    usage: /blesschop
    permission: timberwolf.blesschop
permissions:
  timberwolf.undochop:
    description: Allow player to undo tree chop.
  timberwolf.listchops:
    description: Allow player to list their chops.
  timberwolf.chop:
    description: Allow player to auto-chop trees.
  timberwolf.blesschop:
    description: Allow player to bless a tool for chopping.

